name: gpd-ext
channels:
- conda-forge
- defaults
dependencies:
- geopandas=0.3.0=py35_0
- numpy=1.13.1=py35_0
- pandas=0.20.3=py35_0
- pyepsg=0.3.2=py35_0
- python=3.5.4=0
- pytest=3.2.1=py35_0
- pytest-cov=2.3.1=py35_0
